# Generated by Django 4.1.1 on 2023-01-04 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_sub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=255)),
                ('phonenumber', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('branch', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('joineddate', models.DateTimeField(auto_now_add=True)),
                ('salary', models.IntegerField(default=0)),
                ('assurance', models.CharField(max_length=255)),
                ('bankaccountno', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Addemployee',
        ),
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateField(default=datetime.date(2023, 1, 4)),
        ),
    ]
