# Generated by Django 4.1.1 on 2023-01-06 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_sub', '0002_employees_delete_addemployee_alter_message_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='savedby',
        ),
        migrations.RemoveField(
            model_name='department',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='department',
            name='savedby',
        ),
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateField(default=datetime.date(2023, 1, 7)),
        ),
    ]
